In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.shape

(399, 25)

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [10]:
indep.shape

(399, 27)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [12]:
# split into training set and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB
param_grid = {'alpha': [0.01, 0.1, 0.5, 1.0, 5.0], 'fit_prior': [True, False], 'binarize': [0.0, 0.5, 1.0]}

grid = GridSearchCV(BernoulliNB(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.5, 1.0, 5.0],
                         'binarize': [0.0, 0.5, 1.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [14]:
# print best parameter after tuning
# print(grid.best_params_)
clf=grid.cv_results_
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

# print classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_predictions)

In [15]:
# sample to check f1 macro value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'alpha': 0.01, 'binarize': 0.0, 'fit_prior': True}: 0.9775556904684072

In [16]:
print("BernoulliNB_Confusion Matrix:\n",cm)

BernoulliNB_Confusion Matrix:
 [[51  0]
 [ 3 79]]

In [17]:
print("BernoulliNB_Classification_Report:\n",clf_report)

BernoulliNB_Classification_Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9966523194643712

In [19]:
table=pd.DataFrame.from_dict(clf)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_binarize,param_fit_prior,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.019722,0.001042,0.004209,0.000937,0.01,0.0,True,"{'alpha': 0.01, 'binarize': 0.0, 'fit_prior': ...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
1,0.013756,0.007382,0.004159,0.001028,0.01,0.0,False,"{'alpha': 0.01, 'binarize': 0.0, 'fit_prior': ...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
2,0.005302,0.000744,0.004420,0.001379,0.01,0.5,True,"{'alpha': 0.01, 'binarize': 0.5, 'fit_prior': ...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
3,0.005671,0.001078,0.004041,0.000779,0.01,0.5,False,"{'alpha': 0.01, 'binarize': 0.5, 'fit_prior': ...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
4,0.004019,0.000512,0.004110,0.000489,0.01,1.0,True,"{'alpha': 0.01, 'binarize': 1.0, 'fit_prior': ...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
5,0.004063,0.000543,0.004038,0.000434,0.01,1.0,False,"{'alpha': 0.01, 'binarize': 1.0, 'fit_prior': ...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
6,0.004106,0.000486,0.004112,0.000193,0.10,0.0,True,"{'alpha': 0.1, 'binarize': 0.0, 'fit_prior': T...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
7,0.004029,0.000026,0.003643,0.000817,0.10,0.0,False,"{'alpha': 0.1, 'binarize': 0.0, 'fit_prior': F...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
8,0.003973,0.000848,0.003773,0.001073,0.10,0.5,True,"{'alpha': 0.1, 'binarize': 0.5, 'fit_prior': T...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
9,0.003642,0.001248,0.002230,0.001898,0.10,0.5,False,"{'alpha': 0.1, 'binarize': 0.5, 'fit_prior': F...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,1
10,0.005378,0.002131,0.003534,0.000849,0.10,1.0,True,"{'alpha': 0.1, 'binarize': 1.0, 'fit_prior': T...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
11,0.003722,0.000985,0.003117,0.000923,0.10,1.0,False,"{'alpha': 0.1, 'binarize': 1.0, 'fit_prior': F...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
12,0.003565,0.000999,0.002701,0.001391,0.50,0.0,True,"{'alpha': 0.5, 'binarize': 0.0, 'fit_prior': T...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
13,0.003700,0.002073,0.004659,0.001033,0.50,0.0,False,"{'alpha': 0.5, 'binarize': 0.0, 'fit_prior': F...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
14,0.005412,0.001681,0.003469,0.000748,0.50,0.5,True,"{'alpha': 0.5, 'binarize': 0.5, 'fit_prior': T...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
15,0.003945,0.000528,0.003831,0.000618,0.50,0.5,False,"{'alpha': 0.5, 'binarize': 0.5, 'fit_prior': F...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
16,0.003861,0.000710,0.003546,0.000811,0.50,1.0,True,"{'alpha': 0.5, 'binarize': 1.0, 'fit_prior': T...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
17,0.004158,0.001003,0.004306,0.000580,0.50,1.0,False,"{'alpha': 0.5, 'binarize': 1.0, 'fit_prior': F...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
18,0.003546,0.001350,0.004025,0.000018,1.00,0.0,True,"{'alpha': 1.0, 'binarize': 0.0, 'fit_prior': T...",0.926978,0.962264,0.888515,0.981217,0.981217,0.948038,0.035751,14
19,0.003502,0.000778,0.004112,0.000344,1.00,0.0,False,"{'alpha': 1.0, 'binarize': 0.0, 'fit_prior': F...",0.926978,0.943699,0.888515,0.962573,0.981217,0.940597,0.031751,16
20,0.003614,0.000804,0.003949,0.000478,1.00,0.5,True,"{'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
21,0.004254,0.000619,0.003028,0.000908,1.00,0.5,False,"{'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...",0.926978,0.962264,0.888515,0.962573,0.981217,0.944309,0.032959,15
22,0.004574,0.001458,0.004085,0.001279,1.00,1.0,True,"{'alpha': 1.0, 'binarize': 1.0, 'fit_prior': T...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
23,0.003838,0.001003,0.004027,0.000510,1.00,1.0,False,"{'alpha': 1.0, 'binarize': 1.0, 'fit_prior': F...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
24,0.003883,0.000957,0.003535,0.000729,5.00,0.0,True,"{'alpha': 5.0, 'binarize': 0.0, 'fit_prior': T...",0.926978,0.943699,0.888515,0.944023,0.981217,0.936887,0.030002,17
25,0.003831,0.000501,0.003720,0.000469,5.00,0.0,False,"{'alpha': 5.0, 'binarize': 0.0, 'fit_prior': F...",0.908877,0.906935,0.888515,0.925524,0.981217,0.922214,0.031747,20
26,0.003503,0.000699,0.004706,0.001053,5.00,0.5,True,"{'alpha': 5.0, 'binarize': 0.5, 'fit_prior': T...",0.926978,0.943699,0.888515,0.944023,0.981217,0.936887,0.030002,17
27,0.003657,0.000796,0.003631,0.000505,5.00,0.5,False,"{'alpha': 5.0, 'binarize': 0.5, 'fit_prior': F...",0.908877,0.906935,0.888515,0.944023,0.981217,0.925913,0.032971,19
28,0.003634,0.000501,0.004068,0.000827,5.00,1.0,True,"{'alpha': 5.0, 'binarize': 1.0, 'fit_prior': T...",0.750308,0.805463,0.867217,0.865441,0.842027,0.826091,0.043960,21
29,0.002598,0.001138,0.003675,0.000791,5.00,1.0,False,"{'alpha': 5.0, 'binarize': 1.0, 'fit_prior': F...",0.750308,0.805463,0.830953,0.865441,0.842027,0.818839,0.039323,30

In [20]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pvc:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b 1 or 0:"))
sg_c_input=int(input("sg_c 1 or 0:"))
sg_d_input=int(input("sg_d 1 or 0:"))
sg_e_input=int(input("sg_e 1 or 0:"))
rbc_normal_input=int(input("rbc_normal 1 or 0:"))
pc_normal_input=int(input("pc_normal 1 or 0:"))
pcc_present_input=int(input("pcc_present 1 or 0:"))
ba_present_input=int(input("ba_present 1 or 0:"))
htn_yes_input=int(input("htn_yes 1 or 0:"))
dm_yes_input=int(input("dm_yes 1 or 0:"))
cad_yes_input=int(input("cad_yes 1 or 0:"))
appet_yes_input=int(input("appet_yes 1 or 0:"))
pe_yes_input=int(input("pe_yes 1 or 0:"))
ane_yes_input=int(input("ane_yes 1 or 0:"))

Age: 25
bp: 36
al: 12
su: 45
bgr: 236
bu: 258
sc: 75
sod: 45
pot: 16
hrmo: 32
pvc: 14
wc: 58
rc: 69
sg_b 1 or 0: 1
sg_c 1 or 0: 1
sg_d 1 or 0: 1
sg_e 1 or 0: 0
rbc_normal 1 or 0: 0
pc_normal 1 or 0: 0
pcc_present 1 or 0: 0
ba_present 1 or 0: 0
htn_yes 1 or 0: 0
dm_yes 1 or 0: 0
cad_yes 1 or 0: 0
appet_yes 1 or 0: 0
pe_yes 1 or 0: 0
ane_yes 1 or 0: 0

In [21]:
Future_Prediction = grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, 
                                   sc_input, sod_input, pot_input, hrmo_input, pcv_input, wc_input, 
                                   rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, 
                                   pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                                   cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(